import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Language = 'ar' | 'en';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translationsFull = {
  ar: {
    home: "الرئيسية",
    shop: "المتجر",
    myAccount: "حسابي",
    myOrders: "طلباتي",
    adminPanel: "لوحة التحكم",
    installApp: "تثبيت التطبيق",
    connectWithUs: "تواصل معنا",
    categories: "التصنيفات",
    allProducts: "جميع المنتجات",
    help: "المساعدة",
    terms: "الشروط والأحكام",
    faq: "الأسئلة الشائعة",
    contactUs: "تواصل معنا",
    callUs: "اتصل بنا",
    email: "البريد الإلكتروني",
    whatsapp: "واتساب",
    allRightsReserved: "جميع الحقوق محفوظة",
    madeWithLove: "صنع بحب Qirox Studio",
    signIn: "تسجيل الدخول",
    signOut: "تسجيل الخروج",
    cart: "السلة",
    newCollection: "مجموعة جديدة ٢٠٢٦",
    heroTitle: "أناقة تتجاوز الحدود",
    heroDesc: "نقدم لكم تشكيلة الهوديز الجديدة المصممة بعناية فائقة لتناسب أسلوب حياتكم العصري. جودة استثنائية وتفاصيل تروي قصة إبداع سعودي.",
    discoverCollection: "اكتشف المجموعة",
    featuredItem: "قطعة مميزة",
    exclusivePicks: "المختارات الحصرية",
    viewAllProducts: "عرض جميع المنتجات",
    ourMission: "مهمتنا",
    qualityIsIdentity: "الجودة هي هويتنا",
    brandStoryDesc: "في Qirox Studio، نؤمن أن الملابس ليست مجرد أقمشة، بل هي تعبير عن الشخصية. نحرص على استخدام أجود أنواع القطن والتصاميم التي تجمع بين الراحة القصوى والجمالية العالية.",
    happyCustomers: "عميل سعيد",
    masterCraftsmanship: "صناعة متقنة",
    exceptionalQuality: "جودة استثنائية",
    exceptionalQualityDesc: "خامات مختارة بعناية لضمان التفرد",
    fastShipping: "شحن سريع",
    fastShippingDesc: "توصيل لباب منزلك في أسرع وقت",
    goldenGuarantee: "ضمان ذهبي",
    goldenGuaranteeDesc: "تسوق بكل ثقة مع سياسة استرجاع مرنة",
    stayExclusive: "كن متميزاً",
    newsletterDesc: "كن أول من يعلم عن الإصدارات المحدودة والعروض الحصرية. انضم إلى قائمتنا البريدية.",
    emailPlaceholder: "بريدك الإلكتروني",
    subscribe: "اشتراك",
    fullCollection: "المجموعة كاملة",
    searchPlaceholder: "ابحث عن قطعة فنية...",
    noResults: "لا توجد قطع تطابق بحثك حالياً.",
    productNotFound: "المنتج غير موجود",
    viewDetails: "عرض التفاصيل",
    currency: "ر.س",
    addedToCart: "تمت الإضافة للسلة",
    addedToCartDesc: "أضيف إلى سلة مشترياتك.",
    optionsLabel: "الخيار (اللون / المقاس)",
    colorLabel: "اختر اللون",
    sizeLabel: "اختر المقاس",
    quantityLabel: "الكمية",
    addToCart: "إضافة إلى حقيبة التسوق",
    originalProduct: "قطعة أصلية وحصرية",
    luxuryPackaging: "تغليف فاخر",
    secureShipping: "شحن سريع وآمن",
    featured: "مميز",
    emptyCart: "سلة المشتريات فارغة",
    emptyCartDesc: "لم تقم بإضافة أي منتجات للسلة بعد.",
    shoppingBag: "حقيبة التسوق",
    removeItem: "إزالة القطعة",
    bagSummary: "ملخص الحقيبة",
    subtotal: "المجموع الفرعي",
    tax: "الضريبة (١٥٪)",
    total: "الإجمالي",
    checkout: "إتمام عملية الشراء",
    freeShippingPromo: "شحن مجاني على جميع الطلبات لفترة محدودة",
    orderCheckout: "إتمام الطلب",
    deliveryMethod: "طريقة الاستلام",
    deliveryStorage: "توصيل (Storage Station)",
    pickupFromBranch: "استلام من الفرع",
    selectBranch: "اختر الفرع",
    paymentMethod: "طريقة الدفع",
    cod: "الدفع عند الاستلام",
    bankTransfer: "تحويل بنكي",
    orderSummary: "ملخص الطلب",
    placeOrder: "تأكيد الطلب",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    fullName: "الاسم الكامل",
    phone: "رقم الجوال",
    forgotPassword: "نسيت كلمة المرور؟",
    noAccount: "ليس لديك حساب؟",
    hasAccount: "لديك حساب بالفعل؟",
    technicalSupport: "هل تواجه مشكلة؟ تواصل مع الدعم الفني",
    browseProducts: "تصفح المنتجات"
  },
  en: {
    home: "Home",
    shop: "Shop",
    myAccount: "My Account",
    myOrders: "My Orders",
    adminPanel: "Admin Panel",
    installApp: "Install App",
    connectWithUs: "Connect with us",
    categories: "Categories",
    allProducts: "All Products",
    help: "Help",
    terms: "Terms & Conditions",
    faq: "FAQ",
    contactUs: "Contact Us",
    callUs: "Call Us",
    email: "Email",
    whatsapp: "WhatsApp",
    allRightsReserved: "All rights reserved",
    madeWithLove: "Made with love by Qirox Studio",
    signIn: "Sign In",
    signOut: "Sign Out",
    cart: "Cart",
    newCollection: "New Collection 2026",
    heroTitle: "Elegance Beyond Borders",
    heroDesc: "Introducing our new hoodie collection, meticulously designed to fit your modern lifestyle. Exceptional quality and details telling a story of Saudi creativity.",
    discoverCollection: "Discover Collection",
    featuredItem: "Featured Item",
    exclusivePicks: "Exclusive Picks",
    viewAllProducts: "View All Products",
    ourMission: "Our Mission",
    qualityIsIdentity: "Quality is Our Identity",
    brandStoryDesc: "At Qirox Studio, we believe clothing is more than just fabric; it's an expression of personality. We ensure the use of the finest cotton and designs that combine maximum comfort with high aesthetics.",
    happyCustomers: "Happy Customers",
    masterCraftsmanship: "Master Craftsmanship",
    exceptionalQuality: "Exceptional Quality",
    exceptionalQualityDesc: "Carefully selected materials to ensure uniqueness",
    fastShipping: "Fast Shipping",
    fastShippingDesc: "Delivery to your doorstep in no time",
    goldenGuarantee: "Golden Guarantee",
    goldenGuaranteeDesc: "Shop with confidence with a flexible return policy",
    stayExclusive: "Stay Exclusive",
    newsletterDesc: "Be the first to know about limited releases and exclusive offers. Join our mailing list.",
    emailPlaceholder: "Your Email Address",
    subscribe: "Subscribe",
    fullCollection: "Full Collection",
    searchPlaceholder: "Search for an art piece...",
    noResults: "No pieces match your search currently.",
    productNotFound: "Product not found",
    viewDetails: "View Details",
    currency: "SAR",
    addedToCart: "Added to Cart",
    addedToCartDesc: "has been added to your shopping bag.",
    optionsLabel: "Option (Color / Size)",
    colorLabel: "Select Color",
    sizeLabel: "Select Size",
    quantityLabel: "Quantity",
    addToCart: "Add to Shopping Bag",
    originalProduct: "Original & Exclusive Piece",
    luxuryPackaging: "Luxury Packaging",
    secureShipping: "Fast & Secure Shipping",
    featured: "Featured",
    emptyCart: "Your shopping bag is empty",
    emptyCartDesc: "You haven't added any products to your bag yet.",
    shoppingBag: "Shopping Bag",
    removeItem: "Remove Item",
    bagSummary: "Bag Summary",
    subtotal: "Subtotal",
    tax: "Tax (15%)",
    total: "Total",
    checkout: "Proceed to Checkout",
    freeShippingPromo: "Free shipping on all orders for a limited time",
    orderCheckout: "Order Checkout",
    deliveryMethod: "Collection Method",
    deliveryStorage: "Delivery (Storage Station)",
    pickupFromBranch: "Pickup from Branch",
    selectBranch: "Select Branch",
    paymentMethod: "Payment Method",
    cod: "Cash on Delivery",
    bankTransfer: "Bank Transfer",
    orderSummary: "Order Summary",
    placeOrder: "Confirm Order",
    username: "Username",
    password: "Password",
    login: "Login",
    register: "Register",
    fullName: "Full Name",
    phone: "Phone Number",
    forgotPassword: "Forgot Password?",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    technicalSupport: "Facing an issue? Contact technical support",
    browseProducts: "Browse Products"
  }
};

const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'ar',
      setLanguage: (lang) => {
        set({ language: lang });
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = lang;
      },
      t: (key) => {
        const { language } = get();
        const dict = translationsFull[language] as any;
        return dict[key] || key;
      },
    }),
    {
      name: 'language-storage',
    }
  )
);

export const useLanguage = () => {
  return useLanguageStore();
};
